app/phototainment/views.py
from flask import render_template, request, redirect, url_for, flash, Blueprint, Response
import json
from collections import Counter
from sqlalchemy import desc, func
from sqlalchemy.exc import IntegrityError

import flask_csv

from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import login_user, logout_user, current_user, login_required
from app.privilege import admin, employee
from datetime import datetime, timedelta, time
from app.forms import LoginForm, RegisterForm, EventForm, EditUser, SearchForm, ChangeStatus, CommentForm, AddressForm, \
    ChangePassword, DayRange, TypeForm, CompanyForm, ReportForm
from app.models import db, User, Event, EventType, Client, AdditionalContact, ReferralContact, Comment, EventVenue, \
    login_manager, Company, EventStatus

custom_bp = Blueprint(
    'phototainment',
    __name__,
    template_folder='templates',
    static_folder='static'
)


@login_manager.unauthorized_handler
def unauthorized():
    return redirect(url_for('phototainment.login'))


@custom_bp.route('/login/', methods=["GET", "POST"])
def login():
    form = LoginForm()

    if request.method == "POST":
        req_user = db.session.query(User).filter_by(username=form.username.data.lower()).first()
        if req_user:
            if check_password_hash(pwhash=req_user.password, password=form.password.data):
                login_user(user=req_user)
                return redirect(url_for('phototainment.home'))
            else:
                flash(message="Incorrect Password")
        else:
            flash(message="No user found")
    
    return render_template('login.html', form=form)


@custom_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('phototainment.login'))


@custom_bp.route('/change_password/', methods=["GET", "POST"])
@login_required
def change_password():
    form = ChangePassword()
    if request.method == "POST":
        if check_password_hash(pwhash=current_user.password, password=form.old_password.data):
            new_password = generate_password_hash(password=form.new_password.data, method='pbkdf2:sha256',
                                                  salt_length=8)
            
            if check_password_hash(pwhash=new_password, password=form.confirm_password.data):
                current_user.password = new_password
                db.session.commit()
                flash(message="Your Password has been changed")
                return redirect(url_for('phototainment.home'))
            else:
                flash(message="Password does not match")
        else:
            flash(message="Old password is not correct")
    return render_template('change-password.html', form=form)


@custom_bp.route("/index", methods=["GET", "POST"])
@login_required
@employee
def home():
    events = db.session.query(Event, Client.client_first_name, Client.client_last_name, Client.client_email,
                              Client.primary_contact, ).select_from(Event, Client).join(Client).order_by('event_date')
    
    event_types = db.session.query(EventType).order_by("event_type")
    
    users = db.session.query(User).order_by("username")
    
    recent_bookings = [event for event in events if datetime.now() - event[0].lead_date < timedelta(days=7)]
    
    pending_events = [event for event in events if
                      datetime.now() - event[0].lead_date < timedelta(days=7) and event[0].status_id == 1]
    completed_events = [event for event in events if
                        datetime.now() - event[0].event_date < timedelta(days=7) and event[0].status_id == 4]
    
    upcoming_events = [event for event in events if
                       event[0].event_date - datetime.now() < timedelta(days=7) and event[
                           0].event_date - datetime.now() > timedelta(days=0, minutes=0, seconds=0)]
    
    associated_companies = [company.company_name for company in
                            db.session.query(Company).order_by('company_name').all()]
    months = []
    graph_data1 = []
    graph_data2 = []
    
    for event in events:
        if event[0].lead_date.strftime("%b") in months:
            continue
        else:
            months.append(event[0].lead_date.strftime("%b"))
    for month in months:
        successful_event = 0
        for event in events:
            if event[0].lead_date.strftime("%b") == month and event[0].status_id == 4:
                successful_event += 1
        graph_data1.append(successful_event)

    for month in months:
        number_of_events = 0
        for event in events:
            if event[0].lead_date.strftime("%b") == month:
                number_of_events += 1
        graph_data2.append(number_of_events)
                
        
    
    type_form = TypeForm()
    company_form = CompanyForm()
    
    return render_template(
        "index.html",
        all_bookings=recent_bookings,
        pending_bookings=pending_events,
        completed_bookings=completed_events,
        event_types=event_types,
        upcoming_events=upcoming_events,
        type_form=type_form,
        months=months,
        graph_data1=graph_data1,
        graph_data2=graph_data2,
        event_num=len(upcoming_events),
        company_form=company_form,
        users=users,
        associated_companies=associated_companies
    )


@custom_bp.route("/add_event_type", methods=["POST"])
@login_required
@admin
def add_event_type():
    type_form = TypeForm()
    new_type = EventType(
        event_type=type_form.type_name.data.lower()
    )
    db.session.add(new_type)
    
    try:
        db.session.commit()
        flash("Event type has been added")
    except IntegrityError:
        flash("Event type already exist")
        db.session.rollback()
    
    return redirect(url_for('phototainment.home'))


@custom_bp.route("/add-company", methods=["POST"])
@login_required
def add_company():
    company_form = CompanyForm()
    new_company = Company(
        company_name=company_form.company_name.data.lower()
    )
    db.session.add(new_company)
    
    try:
        db.session.commit()
        flash("New Company has been added")
    except IntegrityError:
        flash("Company already exist")
        db.session.rollback()
    
    return redirect(url_for('phototainment.home'))


@custom_bp.route('/search-client', methods=["GET", "POST"])
@login_required
@employee
def client_table():
    clients = db.session.query(Client).all()
    return render_template('client-table.html', clients=clients)


@custom_bp.route('/delete-client/<client_id>')
@login_required
@admin
def delete_client(client_id):
    requested_client = db.session.query(Client).filter_by(client_id=client_id).first()
    if requested_client.events or requested_client.company:
        flash("Client can not be deleted")
    else:
        db.session.delete(requested_client)
        db.session.commit()
        flash("Client has been deleted")
    return redirect(url_for('phototainment.client_table'))


@custom_bp.route('/register-user', methods=["GET", "POST"])
@login_required
@admin
def register():
    form = RegisterForm()
    if request.method == "POST":
        new_user = User(
            username=form.username.data.lower(),
            password=generate_password_hash(password=form.password.data, method='pbkdf2:sha256', salt_length=8),
            email=form.email.data,
            role_id=form.user_role.data
        )
        db.session.add(new_user)
        db.session.commit()
        flash("New user has been created")
        return redirect(url_for('phototainment.manage_user'))
    return render_template('register.html', form=form)


@custom_bp.route('/manage-user', methods=["GET"])
@login_required
@admin
def manage_user():
    users = db.session.query(User).order_by('id')
    return render_template('manage-users.html', users=users)


@custom_bp.route('/delete-user/<user_id>')
@login_required
@admin
def delete_user(user_id):
    requested_user = db.session.query(User).filter_by(id=user_id).first()
    if requested_user.events or requested_user.comment:
        flash("User can not be deleted")
    else:
        db.session.delete(requested_user)
        db.session.commit()
        flash("User has been deleted")
    return redirect(url_for('phototainment.manage_user'))


@custom_bp.route('/reset-user/<user_id>')
@login_required
@admin
def reset_user(user_id):
    requested_user = db.session.query(User).filter_by(id=user_id).first()
    requested_user.password = generate_password_hash(password="123456", method='pbkdf2:sha256',
                                                  salt_length=8)
    db.session.commit()
    flash("User Password has been reset")
    return redirect(url_for('phototainment.manage_user'))


@custom_bp.route('/edit-user/<user_id>', methods=["GET", "POST"])
@login_required
@admin
def edit_user(user_id):
    requested_user = db.session.query(User).filter_by(id=user_id).first()
    edit_form = EditUser(
        username=requested_user.username,
        user_role=requested_user.role_id,
        email=requested_user.email
    )
    
    if request.method == "POST":
        requested_user.username = edit_form.username.data
        requested_user.role_id = edit_form.user_role.data
        requested_user.email = edit_form.email.data
        db.session.commit()
        return redirect(url_for("phototainment.manage_user"))
    
    return render_template('register.html', form=edit_form)


@custom_bp.route('/_companies', methods=['GET'])
@login_required
@employee
def get_companies():
    companies = [company.company_name.title() for company in db.session.query(Company).all()]
    return Response(json.dumps(companies), mimetype='application/json')


@custom_bp.route('/add-event', methods=["GET", "POST"])
@login_required
@employee
def add_event():
    form = EventForm()
    date_today = datetime.now()
    if request.method == "POST":
        new_client = Client(

app/phototainment/templates/add-address.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Add Address Details{% endblock %}

{% block page_head %}Add Address{% endblock %}



{% block navbar %}{% include 'sidebar.html' %}{% endblock %}
{% block content %}
    <div class="row">








        <div class="col-sm-12 login-main text-center">
            <div class="col-lg-7 col-md-7 col-xs-11 mx-auto float-none login-form">
                <form action="" method="POST" role="form" class="event-form">
                    <div class="row justify-content-around">
                        <div class="form-group required col-6 form-cell">
                            <label class="control-label" for="street_address">Street Address*</label>
                            {{ form.street_address(class="form-control",id="street_address",required="required",type="text", placeholder="Street Address") }}
                        </div>
                        <div class="form-group required col-6 form-cell">
                            <label class="control-label" for="suburb">Suburb*</label>
                            {{ form.suburb(class="form-control",id="suburb",required="required",type="text", placeholder="Suburb") }}
                        </div>
                    </div>
                    <div class="row justify-content-around">
                        <div class="form-group required col-6 form-cell">
                            <label class="control-label" for="state">State*</label>
                            {{ form.state(class="form-control",id="state",required="required",type="text", placeholder="State") }}
                        </div>
                        <div class="form-group required col-6 form-cell">
                            <label class="control-label" for="post_code">Post Code*</label>
                            {{ form.post_code(class="form-control",id="post_code",type="text", placeholder="Post Code") }}
                        </div>
                    </div>
                    {{ form.submit(class="btn btn-success") }}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/phototainment/templates/add_event.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Add Booking{% endblock %}

{% block page_head %}Add Booking{% endblock %}



{% block navbar %}{% include 'sidebar.html' %}{% endblock %}
{% block content %}
<div class="row">
    <div class="col-sm-12 text-center">
        <div class="col-lg-10 col-md-10 col-xs-11 mx-auto float-left text-left">
            {% include 'event-form.html' %}

        </div>
    </div>
</div>
{% endblock %}



{% block custom_scripts %}

<script type="text/javascript">
$(function(){
    $('[type="date"]').prop('min', function(){
        return new Date().toJSON().split('T')[0];
    });
});


    function checkAddContact(elem) {
    if (elem.checked) {
        document.getElementById("additional-contact").classList.remove("d-none");
    }
    else {
        document.getElementById("additional-contact").classList.add("d-none");
    }
}

function checkRefContact(elem) {
    if (elem.checked) {
        document.getElementById("referee-contact").classList.remove("d-none");
    }
    else {
        document.getElementById("referee-contact").classList.add("d-none");
    }
}

document.getElementById('add-lnk').classList.add("active-link");

</script>
{% endblock %}

app/phototainment/templates/charts.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Charts{% endblock %}
{% block page_head %}Charts{% endblock %}


{% block navbar %}{% include 'sidebar.html' %}{% endblock %}
{% block content %}
<div class="row pt-4">
    <div class="col-4">
        <form action="" method="POST" role="form">
            <div class="row">
                <div class="col-8">{{ form.days(class="form-control",id="search_days", type="Select") }}
                </div>
                <div class="col-4">{{ form.submit(class="btn btn-success add-event-btn m-0 float-left") }}</div>
            </div>
        </form>
    </div>
</div>
<div class="tab">
    <button class="tablinks active" onclick="switchTab(event, 'Barchart')">Event Data</button>
    <button class="tablinks" onclick="switchTab(event, 'Piechart')">Successful Events</button>
    <button class="tablinks" onclick="switchTab(event, 'CostChart')">Cost Charts</button>
</div>

<div id="Barchart" class="tabcontent pt-4" style="display:block">
    <div class="col-lg-7 mx-auto">
        <div class="card mb-0">
            <div class="card-body">
                <canvas id="EventChart"></canvas>
            </div>
        </div>
    </div>
</div>


<div id="Piechart" class="tabcontent pt-4">
    <div class="col-lg-7 mx-auto">
        <div class="card mb-0">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-10 mx-auto">
                        <canvas id="SuccessfulEvents"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="CostChart" class="tabcontent pt-4">
    <div class="row">
        <div class="col-lg-6 mx-auto">
            <div class="card mb-0">
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-10 mx-auto">
                            <canvas id="barChart1"></canvas>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 mx-auto">
            <div class="card mb-0">
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-10 mx-auto">
                            <canvas id="pieChartExample"></canvas>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


{% endblock %}

{% block custom_scripts %}
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<script type="text/javascript">
function switchTab(evt, filter) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }
  document.getElementById(filter).style.display = "block";
  evt.currentTarget.className += " active";
}


document.getElementById('charts-lnk').classList.add("active-link");

let pie_label = [];
let pie_data = [];

{% for data in doughnut_chart_data %}
                pie_label.push('{{data}}')
                pie_data.push('{{doughnut_chart_data[data]}}')
              {% endfor %}

let bar_label =  [];
let bar_data =  [];

{% for data in bar_graph_data %}
                bar_label.push('{{data}}')
                bar_data.push('{{bar_graph_data[data]}}')
              {% endfor %}


var months = {{ months|tojson }}
        let graph_labels = months;
        let graph_data2 = {{ graph_data2 }};


var event_type = {{ available_types|tojson }}
        let cost_chart_label = event_type;
        let cost_chart_data = {{ events_revenue }};





</script>
<script src="{{ url_for('static', filename='js/charts/Chart.js') }}"></script>
<script src="{{ url_for('static', filename='js/charts/charts-main.js') }}"></script>
{% endblock %}

app/phototainment/templates/client-table.html
{% extends 'base.html' %}

{% block title %}Manage Events{% endblock %}
{% block page_head %}Clients{% endblock %}


{% block navbar %}{% include 'sidebar.html' %}{% endblock %}
{% block content %}
<table id="table2" class="table mb-0 table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>First Name</th>
                                    <th>Last Name</th>
                                    <th>Email</th>
                                    <th>Contact</th>
                                    <th>Company</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for client in clients %}
                                <tr>
                                    <td><a href="#">{{client.client_first_name.title()}}</a></td>
                                    <td>{{client.client_last_name}}</td>
                                    <td>{{client.client_email}}</td>
                                    <td>{{client.primary_contact}}</td>
                                    <td>{% if client.company %} {{client.company.company_name.title()}}{% endif %}</td>
                                    <td>
                                        <a class="edit-btn"
                           href="#">
                            <svg xmlns="http://www.w3.org/2000/svg" width="17.846" height="17.849"
                                 viewBox="0 0 17.846 17.849">
                                <path id="edit_baseline"
                                      d="M4.5,18.627v3.718H8.217L19.181,11.38,15.464,7.662ZM22.056,8.5a.988.988,0,0,0,0-1.4l-2.32-2.32a.987.987,0,0,0-1.4,0L16.525,6.6l3.717,3.718L22.056,8.5Z"
                                      transform="translate(-4.5 -4.496)" fill="#f39800"/>
                            </svg>

                        </a>
                        {% if current_user.role.role_id == 1 %}
                        <button class="delete-btn"
                                onclick="deleteEvent('{{ url_for('phototainment.delete_client', client_id=client.client_id) }}')">
                            <svg xmlns="http://www.w3.org/2000/svg" width="14.737" height="17.849"
                                 viewBox="0 0 14.737 17.849">
                                <path id="delete_baseline"
                                      d="M8.553,20.366a2.053,2.053,0,0,0,2.105,1.983h8.421a2.053,2.053,0,0,0,2.105-1.983V8.466H8.553ZM22.237,5.492H18.553L17.5,4.5H12.237l-1.053.992H7.5V7.475H22.237Z"
                                      transform="translate(-7.5 -4.5)" fill="#f39800"/>
                            </svg>

                        </button>
                        {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>

{% endblock %}
{% block custom_scripts %}
<script>
        function deleteEvent(redirect) {
            var txt;
            var isAdd = confirm("Do you want to delete the selected event?");
            if (isAdd == true) {
                window.location.href = redirect;
            }
        }
</script>

<script type="text/javascript">
   $(function() {
    $("#table2").dataTable({
        "iDisplayLength": 10,
        "aLengthMenu": [[10, 25, 50,  -1], [10, 25, 50, "All"]]
       });
   });
   table.destroy();
  </script>
<script src="{{ url_for('static', filename='js/datatables/jquery.dataTables.js') }}" type="text/javascript"></script>
<script src="{{ url_for('static', filename='js/datatables/dataTables.bootstrap.js') }}" type="text/javascript"></script>
{% endblock %}

app/phototainment/templates/event-form.html
<form action="" method="POST" role="form" class="event-form pt-5">
    <h4 class="text-left">Event Details</h4>

    <div class="row justify-content-around">
        <div class="form-group required col-8 form-cell">
            <label class="control-label" for="event_name">Event Name*</label>
            {{ form.event_name(class="form-control",id="event_name", required="required",
            type="text", placeholder="Event Name", autocomplete='off') }}
        </div>
        <div class="form-group required col-4 form-cell">
            <label class="control-label" for="event_type">Event Type*</label>
            {{ form.event_type(class="form-control",id="event_type", required="required",
            type="Select") }}
        </div>
    </div>
    <div class="row justify-content-around">

        <div class="form-group required col-4 form-cell">
            <label class="control-label" for="event_date">Event Date*</label>
            {{ form.event_date(class="form-control datepicker",id="event_date", required="required",
            type="Date") }}
        </div>
        <div class="form-group required col-4 form-cell">
            <label class="control-label" for="start_time">Start time*</label>
            {{ form.start_time(class="form-control", id="start_time", required="required",
            type="Time") }}
        </div>
        <div class="form-group required col-4">
            <label class="control-label" for="duration">Duration in hrs*</label>
            {{ form.duration(class="form-control",id="duration", type="Text", placeholder="1 to 2 hrs", autocomplete='off') }}
        </div>
    </div>

    <h4 class="text-left">Primary Contact</h4>

    <div class="row justify-content-around">
        <div class="form-group required col-4 form-cell">
            <label class="control-label" for="first_name">First Name*</label>
            {{
            form.first_name(class="form-control",id="first_name",required="required",type="text",
            placeholder="First Name", autocomplete='off') }}
        </div>
        <div class="form-group required col-4 form-cell">
            <label class="control-label" for="last_name">Last Name*</label>
            {{ form.last_name(class="form-control",id="last_name",required="required",type="text",
            placeholder="Last Name", autocomplete='off') }}
        </div>
        <div class="form-group required col-4 form-cell">
            <label class="control-label" for="company">Company Name</label>
            {{ form.company(class="form-control",id="company", type="text",
            placeholder="Company", id="company_autocomplete") }}
        </div>
    </div>

    <div class="row justify-content-around">
        <div class="form-group required col-6 form-cell">
            <label class="control-label" for="client_email">Email*</label>
            {{
            form.client_email(class="form-control",id="client_email",required="required",type="text",
            placeholder="Enter email", autocomplete='off') }}
        </div>
        <div class="form-group required col-6 form-cell">
            <label class="control-label" for="phone_num">Primary Contact*</label>
            {{ form.primary_contact(class="form-control",id="phone_num", required="required",
            type="tel", oninvalid="this.setCustomValidity('Please enter a valid mobile number')",
                oninput="this.setCustomValidity('')",
                pattern="[0-9]{9}",
                placeholder="423314422", autocomplete='off')}}
        </div>
    </div>

    <div class="row">
        <div class="form-group required col-4 form-cell">
            <label class="control-label" for="estimated_cost">Estimated Cost</label>
            {{
            form.estimated_cost(class="form-control",id="estimated_cost",type="number",
            placeholder="$123", autocomplete='off') }}
        </div>
    </div>

    <div class="col-12 px-0 py-3 text-left ck-box">
        <input type="checkbox" id="check-additional-contact" name="check-additional-contact"
               onchange="checkAddContact(this);">
        <label for="check-additional-contact">Add Secondary Contact</label>
    </div>

    <div class="col-12 p-0 d-none" id="additional-contact">
        <h4 class="text-left">Secondary Contact</h4>
        <div class="row justify-content-around">
            <div class="form-group required col-6 form-cell">
                <label class="control-label" for="alt_contact_name">Name</label>
                {{ form.alt_contact_name(class="form-control",id="alt_contact_name", type="text",
                placeholder="Contact Person", autocomplete='off') }}
            </div>
            <div class="form-group required col-6 form-cell">
                <label class="control-label" for="alt_contact">Contact #2</label>
                {{
                form.alt_contact(class="form-control",id="alt_contact",type="tel",
                oninput="this.setCustomValidity('')",
                pattern="[0-9]{9}",
                placeholder="423314422",
                placeholder="Secondary Contact", autocomplete='off') }}
            </div>
        </div>
    </div>


    <div class="col-12 px-0 py-3 text-left ck-box">
        <input type="checkbox" id="check-referee-contact" name="check-referee-contact"
               onchange="checkRefContact(this);">
        <label for="check-referee-contact">Add referral details</label>
    </div>

    <div class="col-12 p-0 d-none" id="referee-contact">
        <h4 class="text-left">Referred by Contact</h4>
        <div class="row justify-content-around">
            <div class="form-group required col-6 form-cell">
                <label class="control-label" for="referrer_name">Referred By</label>
                {{ form.referrer_name(class="form-control",id="referrer_name", type="text",
                placeholder="Contact Person", autocomplete='off') }}
            </div>
            <div class="form-group required col-6 form-cell">
                <label class="control-label" for="referrer_contact">Contact</label>
                {{
                form.referrer_contact(class="form-control", id="referrer_contact",type="tel",
                oninput="this.setCustomValidity('')",
                pattern="[0-9]{9}",
                placeholder="423314422", autocomplete='off') }}
            </div>
        </div>
    </div>

    <h4 class="text-left mt-4">Additional Information</h4>
    <div class="row justify-content-around">
        <div class="col-12">
            {{ ckeditor.load() }}
            {{ ckeditor.config(name='additional_information') }}
            {{ form.additional_information(class="form-control col-12",id="additional_information",
            type="text") }}
        </div>
    </div>

    {{ form.submit(class="btn btn-success add-event-btn") }}
</form>



<link rel="stylesheet" href="{{ url_for('static', filename='css/jquery-ui.css') }}">
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>
    $(function() {
        $.ajax({
            url: '{{ url_for("phototainment.get_companies") }}'
            }).done(function (data){
                $('#company_autocomplete').autocomplete({
                    source: data,
                    minLength: 2
                });
            });
        });
</script>

app/phototainment/templates/search-event.html
{% extends 'base.html' %}

{% block title %}Manage Events{% endblock %}
{% block page_head %}Manage Events{% endblock %}


{% block navbar %}{% include 'sidebar.html' %}{% endblock %}
{% block content %}
<div class="row m-0 pt-4">
    <div class="text-center search-outer p-0">
        <div class="form-group required">

            <div class="col-sm-9 p-0">
                <form action="" method="POST" role="search" class="search-form">
                    <div class="input-group">
                        {{ form.search(class="form-control search-field",id="search",type="text") }}
                        <button class="btn btn-outline-secondary dropdown-toggle" type="button"
                                data-bs-toggle="dropdown" aria-expanded="false">Search By
                        </button>
                        <ul class="dropdown-menu shadow-sm text-left">
                            <li>{{ form.search_fname(class="btn search-btn dropdown-btn") }}</li>
                            <li>{{ form.search_lname(class="btn search-btn dropdown-btn") }}</li>
                            <li>{{ form.search_email(class="btn search-btn dropdown-btn") }}</li>
                            <li>{{ form.search_contact(class="btn search-btn dropdown-btn") }}</li>
                            <li>{{ form.search_evname(class="btn search-btn dropdown-btn") }}</li>
                            <li>{{ form.search_evtype(class="btn search-btn dropdown-btn") }}</li>
                            <li>{{ form.search_staff(class="btn search-btn dropdown-btn") }}</li>
                            <li>{{ form.search_status(class="btn search-btn dropdown-btn") }}</li>
                        </ul>
                    </div>
                </form>
            </div>

            <a href="{{ url_for('phototainment.add_event') }}" class="add-btn btn btn-success ml-4">Add New Booking</a>
        </div>
    </div>
</div>

{% include 'events-table.html' %}

{% endblock %}

{% block custom_scripts %}
<script type="text/javascript">
             $(document).ready(function () {
                 $('.search-dropdown-toggle').on('click', function () {
                     $('.search-dropdown-menu').toggleClass('show');
                 });
             });
             $(document).ready(function () {
                 $('.sort-dropdown-toggle').on('click', function () {
                     $('.sort-dropdown-menu').toggleClass('show');
                 });
             });
document.getElementById('search-lnk').classList.add("active-link");

</script>

<script type="text/javascript">
   $(function() {
    $("#table1").dataTable({
        "iDisplayLength": 10,
        "aLengthMenu": [[10, 25, 50,  -1], [10, 25, 50, "All"]]
       });
   });
   table.destroy();
  </script>

{% endblock %}