app/phototainment/views.py
from flask import render_template, request, redirect, url_for, flash, Blueprint, Response
import json
from collections import Counter
from sqlalchemy import desc, func
from sqlalchemy.exc import IntegrityError

import flask_csv

from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import login_user, logout_user, current_user, login_required
from app.privilege import admin, employee
from datetime import datetime, timedelta, time
from app.forms import LoginForm, RegisterForm, EventForm, EditUser, SearchForm, ChangeStatus, CommentForm, AddressForm, \
    ChangePassword, DayRange, TypeForm, CompanyForm, ReportForm
from app.models import db, User, Event, EventType, Client, AdditionalContact, ReferralContact, Comment, EventVenue, \
    login_manager, Company, EventStatus

custom_bp = Blueprint(
    'phototainment',
    __name__,
    template_folder='templates',
    static_folder='static'
)


@login_manager.unauthorized_handler
def unauthorized():
    return redirect(url_for('phototainment.login'))


@custom_bp.route('/login/', methods=["GET", "POST"])
def login():
    form = LoginForm()

    if request.method == "POST":
        req_user = db.session.query(User).filter_by(username=form.username.data.lower()).first()
        if req_user:
            if check_password_hash(pwhash=req_user.password, password=form.password.data):
                login_user(user=req_user)
                return redirect(url_for('phototainment.home'))
            else:
                flash(message="Incorrect Password")
        else:
            flash(message="No user found")
    
    return render_template('login.html', form=form)


@custom_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('phototainment.login'))


@custom_bp.route('/change_password/', methods=["GET", "POST"])
@login_required
def change_password():
    form = ChangePassword()
    if request.method == "POST":
        if check_password_hash(pwhash=current_user.password, password=form.old_password.data):
            new_password = generate_password_hash(password=form.new_password.data, method='pbkdf2:sha256',
                                                  salt_length=8)
            
            if check_password_hash(pwhash=new_password, password=form.confirm_password.data):
                current_user.password = new_password
                db.session.commit()
                flash(message="Your Password has been changed")
                return redirect(url_for('phototainment.home'))
            else:
                flash(message="Password does not match")
        else:
            flash(message="Old password is not correct")
    return render_template('change-password.html', form=form)


@custom_bp.route("/index", methods=["GET", "POST"])
@login_required
@employee
def home():
    events = db.session.query(Event, Client.client_first_name, Client.client_last_name, Client.client_email,
                              Client.primary_contact, ).select_from(Event, Client).join(Client).order_by('event_date')
    
    event_types = db.session.query(EventType).order_by("event_type")
    
    users = db.session.query(User).order_by("username")
    
    recent_bookings = [event for event in events if datetime.now() - event[0].lead_date < timedelta(days=7)]
    
    pending_events = [event for event in events if
                      datetime.now() - event[0].lead_date < timedelta(days=7) and event[0].status_id == 1]
    completed_events = [event for event in events if
                        datetime.now() - event[0].event_date < timedelta(days=7) and event[0].status_id == 4]
    
    upcoming_events = [event for event in events if
                       event[0].event_date - datetime.now() < timedelta(days=7) and event[
                           0].event_date - datetime.now() > timedelta(days=0, minutes=0, seconds=0)]
    
    associated_companies = [company.company_name for company in
                            db.session.query(Company).order_by('company_name').all()]
    months = []
    graph_data1 = []
    graph_data2 = []
    
    for event in events:
        if event[0].lead_date.strftime("%b") in months:
            continue
        else:
            months.append(event[0].lead_date.strftime("%b"))
    for month in months:
        successful_event = 0
        for event in events:
            if event[0].lead_date.strftime("%b") == month and event[0].status_id == 4:
                successful_event += 1
        graph_data1.append(successful_event)

    for month in months:
        number_of_events = 0
        for event in events:
            if event[0].lead_date.strftime("%b") == month:
                number_of_events += 1
        graph_data2.append(number_of_events)
                
        
    
    type_form = TypeForm()
    company_form = CompanyForm()
    
    return render_template(
        "index.html",
        all_bookings=recent_bookings,
        pending_bookings=pending_events,
        completed_bookings=completed_events,
        event_types=event_types,
        upcoming_events=upcoming_events,
        type_form=type_form,
        months=months,
        graph_data1=graph_data1,
        graph_data2=graph_data2,
        event_num=len(upcoming_events),
        company_form=company_form,
        users=users,
        associated_companies=associated_companies
    )


@custom_bp.route("/add_event_type", methods=["POST"])
@login_required
@admin
def add_event_type():
    type_form = TypeForm()
    new_type = EventType(
        event_type=type_form.type_name.data.lower()
    )
    db.session.add(new_type)
    
    try:
        db.session.commit()
        flash("Event type has been added")
    except IntegrityError:
        flash("Event type already exist")
        db.session.rollback()
    
    return redirect(url_for('phototainment.home'))


@custom_bp.route("/add-company", methods=["POST"])
@login_required
def add_company():
    company_form = CompanyForm()
    new_company = Company(
        company_name=company_form.company_name.data.lower()
    )
    db.session.add(new_company)
    
    try:
        db.session.commit()
        flash("New Company has been added")
    except IntegrityError:
        flash("Company already exist")
        db.session.rollback()
    
    return redirect(url_for('phototainment.home'))


@custom_bp.route('/search-client', methods=["GET", "POST"])
@login_required
@employee
def client_table():
    clients = db.session.query(Client).all()
    return render_template('client-table.html', clients=clients)


@custom_bp.route('/delete-client/<client_id>')
@login_required
@admin
def delete_client(client_id):
    requested_client = db.session.query(Client).filter_by(client_id=client_id).first()
    if requested_client.events or requested_client.company:
        flash("Client can not be deleted")
    else:
        db.session.delete(requested_client)
        db.session.commit()
        flash("Client has been deleted")
    return redirect(url_for('phototainment.client_table'))


@custom_bp.route('/register-user', methods=["GET", "POST"])
@login_required
@admin
def register():
    form = RegisterForm()
    if request.method == "POST":
        new_user = User(
            username=form.username.data.lower(),
            password=generate_password_hash(password=form.password.data, method='pbkdf2:sha256', salt_length=8),
            email=form.email.data,
            role_id=form.user_role.data
        )
        db.session.add(new_user)
        db.session.commit()
        flash("New user has been created")
        return redirect(url_for('phototainment.manage_user'))
    return render_template('register.html', form=form)


@custom_bp.route('/manage-user', methods=["GET"])
@login_required
@admin
def manage_user():
    users = db.session.query(User).order_by('id')
    return render_template('manage-users.html', users=users)


@custom_bp.route('/delete-user/<user_id>')
@login_required
@admin
def delete_user(user_id):
    requested_user = db.session.query(User).filter_by(id=user_id).first()
    if requested_user.events or requested_user.comment:
        flash("User can not be deleted")
    else:
        db.session.delete(requested_user)
        db.session.commit()
        flash("User has been deleted")
    return redirect(url_for('phototainment.manage_user'))


@custom_bp.route('/reset-user/<user_id>')
@login_required
@admin
def reset_user(user_id):
    requested_user = db.session.query(User).filter_by(id=user_id).first()
    requested_user.password = generate_password_hash(password="123456", method='pbkdf2:sha256',
                                                  salt_length=8)
    db.session.commit()
    flash("User Password has been reset")
    return redirect(url_for('phototainment.manage_user'))


@custom_bp.route('/edit-user/<user_id>', methods=["GET", "POST"])
@login_required
@admin
def edit_user(user_id):
    requested_user = db.session.query(User).filter_by(id=user_id).first()
    edit_form = EditUser(
        username=requested_user.username,
        user_role=requested_user.role_id,
        email=requested_user.email
    )
    
    if request.method == "POST":
        requested_user.username = edit_form.username.data
        requested_user.role_id = edit_form.user_role.data
        requested_user.email = edit_form.email.data
        db.session.commit()
        return redirect(url_for("phototainment.manage_user"))
    
    return render_template('register.html', form=edit_form)


@custom_bp.route('/_companies', methods=['GET'])
@login_required
@employee
def get_companies():
    companies = [company.company_name.title() for company in db.session.query(Company).all()]
    return Response(json.dumps(companies), mimetype='application/json')


@custom_bp.route('/add-event', methods=["GET", "POST"])
@login_required
@employee
def add_event():
    form = EventForm()
    date_today = datetime.now()
    if request.method == "POST":
        new_client = Client(

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/all.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/theme.css') }}">


    <script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/bootstrap/bootstrap.bundle.min.js') }}"
            type="text/javascript"></script>

</head>
<body>


<div class="wrapper">
    <div class="navbar-header">
        <!-- Navbar Brand --><a class="navbar-brand d-none d-sm-inline-block" href="index.html">
        <a class="menu-btn active" id="toggle-btn" href="#"><span></span><span></span><span></span></a>
        <div class="brand-img d-none d-lg-inline-block">
            <a href="{{ url_for('phototainment.home') }}"> <img
                src="{{ url_for('static', filename='img/logo.png') }}"
                alt="logo"/>
                </a>
        </div>


    </a>
    </div>
    <div class="page-body row m-0">
        {% block navbar %}{% endblock %}
        <div id="main-content" class="content-inner col-xs-12 col-xl-10">
            <!-- Page Header-->

            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}
            <div id="message-out" class="alert alert-warning mt-4">
                <button type="button" onclick="closeMessage()" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}

            <header class="bg-white shadow-sm mt-4 px-4 py-3 z-index-20">
                <div class="container-fluid px-0">
                    <h2 class="mb-0 p-1">{% block page_head %}{% endblock %}</h2>
                </div>
            </header>

            {% block content %}{% endblock %}
            {% block side_bar %}{% endblock %}

        </div>
    </div>
</div>

<script>
      // ------------------------------------------------------- //
      //   Inject SVG Sprite -
      //   see more here
      //   https://css-tricks.com/ajaxing-svg-sprite/
      // ------------------------------------------------------ //
      function injectSvgSprite(path) {

          var ajax = new XMLHttpRequest();
          ajax.open("GET", path, true);
          ajax.send();
          ajax.onload = function(e) {
          var div = document.createElement("div");
          div.className = 'd-none';
          div.innerHTML = ajax.responseText;
          document.body.insertBefore(div, document.body.childNodes[0]);
          }
      }
      // this is set to BootstrapTemple website as you cannot
      // inject local SVG sprite (using only 'icons/orion-svg-sprite.svg' path)
      // while using file:// protocol
      // pls don't forget to change to your domain :)
      injectSvgSprite('https://bootstraptemple.com/files/icons/orion-svg-sprite.svg');





</script>

{% block custom_scripts %}{% endblock %}
<script type="text/javascript">
             {% if request.url_rule.endpoint == "login" %}
                document.getElementById('content').classList.add("bg-none");
             {% endif %}
    function closeMessage() {
        document.getElementById('message-out').classList.add("d-none");
        }

</script>
<script src="{{ url_for('static', filename='js/all.js') }}" type="text/javascript"></script>

<script src="{{ url_for('static', filename='js/theme.js') }}" type="text/javascript"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
      integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</body>
</html>

app/templates/change-password.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Change Password{% endblock %}

{% block page_head %}Change Password{% endblock %}


{% block navbar %}{% include 'sidebar.html' %}{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12 login-main text-center">
            <div class="col-lg-6 col-md-7 col-xs-11 mx-auto float-none login-form">
                <div class="col-lg-12 bg-white">
                    <div class="d-flex align-items-center h-100">
                        <form class="py-3 w-100" method="post">
                            <div class="input-material-group mb-3">
                                {{ form.old_password(class="input-material form-control",id="old_password",
                                required="required", type="password", autocomplete="off", placeholder="") }}
                                <label class="label-material form-label control-label " for="old_password">Old
                                    Password</label>
                            </div>

                            <div class="input-material-group mb-4">
                                {{ form.new_password(class="input-material form-control",id="new_password",
                                required="required", type="password", autocomplete="off", placeholder="") }}
                                <label class="label-material form-label control-label " for="new_password">New
                                    Password</label>
                            </div>

                            <div class="input-material-group mb-4">
                                {{ form.confirm_password(class="input-material form-control",id="confirm_password",
                                required="required", type="password", autocomplete="off", placeholder="") }}
                                <label class="label-material form-label control-label " for="confirm_password">Confirm
                                    Password</label>
                            </div>

                            <button class="btn btn-primary mb-3 btn-sm" id="login" type="submit">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/forgot-password.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Forgot Password{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12 login-main text-center">
                <div class="col-lg-6 col-md-7 col-xs-11 mx-auto float-none login-form">
                    {{ wtf.quick_form(form) }}

                    {% with messages = get_flashed_messages() %}
                        {% if messages %}
                            {% for message in messages %}
                                <p>{{ message }}</p>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/theme.css') }}">


    <script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/bootstrap/bootstrap.bundle.min.js') }}"
            type="text/javascript"></script>

</head>
<body>


<div class="container">
    <div class="row">
        <div class="col-sm-12 login-main text-center">
            <div class="col-lg-5 col-md-6 col-xs-11 mx-auto float-none login-form">

                <div class="col-lg-12 bg-white">
                    <img class="w-100"
                src="{{ url_for('static', filename='img/logo.png') }}"
                alt="logo"/>
                    <div class="d-flex align-items-center h-100">
                        <form class="py-3 w-100" method="post">
                            <div class="input-material-group mb-3">
                                {{ form.username(class="input-material form-control",id="username",
                                required="required", type="text", autocomplete="off", placeholder="") }}
                                <label class="label-material form-label control-label " for="username">Username</label>

                            </div>
                            <div class="input-material-group mb-4">

                                {{ form.password(class="input-material form-control",id="password",
                                required="required", type="password", autocomplete="off", placeholder="") }}
                                <label class="label-material form-label control-label " for="password">Password</label>


                            </div>
                            {{ form.submit(class="btn btn-success mb-3 btn-sm",id="submit", type="submit", value="Login") }}
<!--                            <br><a class="text-sm text-paleBlue" href="#">Forgot Password?</a><br>-->
                        </form>
                    </div>
                </div>

                {% with messages = get_flashed_messages() %}
                {% if messages %}
                {% for message in messages %}
                <p>{{ message }}</p>
                {% endfor %}
                {% endif %}
                {% endwith %}
            </div>
        </div>
    </div>
</div>


    <script src="{{ url_for('static', filename='js/theme.js') }}" type="text/javascript"></script>
</body>
</html>

app/templates/manage-users.html
{% extends 'base.html' %}
{% block title %}Manage User{% endblock %}

{% block page_head %}Manage Users{% endblock %}


{% block navbar %}{% include 'sidebar.html' %}{% endblock %}
{% block content %}
<div class="row d-flex justify-content-end">
    <div class="col-3"><a href="{{ url_for('phototainment.register') }}" class="add-btn btn btn-success my-3">Add New User</a></div>
</div>
<div class="row m-0">
    <div class="table-responsive">
        <table class="table mb-0 table-striped table-hover">
            <thead>
            <tr>
                <th>Id</th>
                <th>User Name</th>
                <th>Role</th>
                <th>Email</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
            {% if not user.id == 1 %}
            <tr>
                <td>{{user.id}}</td>
                <td>{{user.username.title()}}</td>
                <td>{{user.role.role_name}}</td>
                <td>{{user.email}}</td>
                <td><a class="edit-btn"
                       href="{{ url_for('phototainment.edit_user', user_id=user.id) }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="17.846" height="17.849"
                         viewBox="0 0 17.846 17.849">
                        <path id="edit_baseline"
                              d="M4.5,18.627v3.718H8.217L19.181,11.38,15.464,7.662ZM22.056,8.5a.988.988,0,0,0,0-1.4l-2.32-2.32a.987.987,0,0,0-1.4,0L16.525,6.6l3.717,3.718L22.056,8.5Z"
                              transform="translate(-4.5 -4.496)" fill="#f39800"/>
                    </svg>

                </a>

                    <button class="delete-btn"
                            onclick="deleteUser('{{ url_for('phototainment.delete_user', user_id=user.id) }}')">
                        <svg xmlns="http://www.w3.org/2000/svg" width="14.737" height="17.849"
                             viewBox="0 0 14.737 17.849">
                            <path id="delete_baseline"
                                  d="M8.553,20.366a2.053,2.053,0,0,0,2.105,1.983h8.421a2.053,2.053,0,0,0,2.105-1.983V8.466H8.553ZM22.237,5.492H18.553L17.5,4.5H12.237l-1.053.992H7.5V7.475H22.237Z"
                                  transform="translate(-7.5 -4.5)" fill="#f39800"/>
                        </svg>

                    </button>
                    <button class="reset-user delete-btn" onclick="resetUser('{{ url_for('phototainment.reset_user', user_id=user.id) }}')">
                    <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="undo" class="svg-inline--fa fa-undo fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="#FFA101" d="M212.333 224.333H12c-6.627 0-12-5.373-12-12V12C0 5.373 5.373 0 12 0h48c6.627 0 12 5.373 12 12v78.112C117.773 39.279 184.26 7.47 258.175 8.007c136.906.994 246.448 111.623 246.157 248.532C504.041 393.258 393.12 504 256.333 504c-64.089 0-122.496-24.313-166.51-64.215-5.099-4.622-5.334-12.554-.467-17.42l33.967-33.967c4.474-4.474 11.662-4.717 16.401-.525C170.76 415.336 211.58 432 256.333 432c97.268 0 176-78.716 176-176 0-97.267-78.716-176-176-176-58.496 0-110.28 28.476-142.274 72.333h98.274c6.627 0 12 5.373 12 12v48c0 6.627-5.373 12-12 12z"></path></svg></button>
                </td>
            </tr>
            {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

{% block custom_scripts %}
<script>
        function deleteUser(redirect) {
            var txt;
            var isAdd = confirm("Do you want to delete the selected user?");
            if (isAdd == true) {
                window.location.href = redirect;
            }
        }
        function editUser(redirect) {
            window.location.href = redirect;
        }


        function resetUser(redirect) {
            var txt;
            var isAdd = confirm("Do you want to reset password the selected user?");
            if (isAdd == true) {
                window.location.href = redirect;
            }
        }



</script>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Add User{% endblock %}

{% block page_head %}Add User{% endblock %}


{% block navbar %}{% include 'sidebar.html' %}{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-sm-12 login-main">


            <div class="col-lg-5 col-md-6 col-xs-11 mx-auto float-none login-form">

                <div class="col-lg-12 bg-white">
                    <div class="d-flex align-items-center h-100">
                        <form class="py-3 w-100 text-center" method="post">
                            <div class="input-material-group mb-3">
                                {{ form.username(class="input-material form-control",id="username",
                                required="required", type="text", autocomplete="off", placeholder="") }}
                                <label class="label-material form-label control-label " for="username">Username</label>
                            </div>

                            <div class="input-material-group mb-4">
                                {{ form.email(class="input-material form-control",id="email",
                                required="required", type="email", autocomplete="off", placeholder="") }}
                                <label class="label-material form-label control-label " for="email">Email</label>
                            </div>

                            {% if form.password %}
                            <div class="input-material-group mb-4">
                                {{ form.password(class="input-material form-control", id="password",
                                required="required", type="password", autocomplete="off", placeholder="") }}
                                <label class="label-material form-label control-label " for="password">Password</label>
                            </div>
                            {% endif %}

                            <div class="input-material-group mb-4">
                                {{ form.user_role(class="form-control",id="user_role", required="required", type="Select") }}
                            </div>

                            {{ form.submit(class="btn btn-primary mb-3 btn-sm") }}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/right-bar.html
<div class="right-bar col-xl-2 col-lg-3 col-md-3">
    <div class="row py-4 greeting-outer">
        <div class="col-lg-7 greeting-img">
            <img src="{{ url_for('static', filename='img/user.png') }}" alt="user"/>
        </div>
        <div class="col-lg-5 text-left greeting-txt">
            <p class="m-0">Hello</p>
            <p class="m-0">{{ current_user.username.title() }}</p>
        </div>

    </div>
    <div class="row">
        <div class="bar-quick-links col-12 p-0">
            <ul>
                <li><a href="#">Search Customer</a></li>
                <li><a href="{{ url_for('phototainment.generate_report') }}">Download report</a></li>
                {% if current_user.role.role_id == 1 %}
                <li><a href="{{ url_for('phototainment.register') }}">Add User</a></li>
                <li><a href="{{ url_for('phototainment.manage_user') }}">Manage User</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

app/templates/sidebar.html
<nav class="side-navbar z-index-40 col-2 p-0">
          <!-- Sidebar Header-->
          <div class="sidebar-header d-flex align-items-center py-4 px-3"><img class="avatar shadow-0 img-fluid rounded-circle" src="{{ url_for('static', filename='img/user.png') }}" alt="...">
            <div class="ms-3 title">
              <h1 class="h4 ml-2">{{ current_user.username.title() }}</h1>

            </div>
          </div>
          <ul class="list-unstyled py-4">
            <li class="sidebar-item"><a id="dashboard-lnk" class="sidebar-link" href="{{ url_for('phototainment.home') }}">
                <svg class="svg-icon svg-icon-sm svg-icon-heavy mr-xl-2">
                  <use xlink:href="#real-estate-1"> </use>
                </svg>Home </a>
            </li>
              {% if current_user.role.role_id == 1 %}
              <li class="sidebar-item"><a id="charts-lnk" class="sidebar-link" href="{{ url_for('phototainment.charts') }}">
                <svg class="svg-icon svg-icon-sm svg-icon-heavy mr-xl-2">
                  <use xlink:href="#sales-up-1"> </use>
                </svg>Charts </a>
                  {% endif %}
            </li>
              <li class="sidebar-item"><a id="upcoming-lnk" class="sidebar-link" href="{{ url_for('phototainment.upcoming_events') }}">
                <svg class="svg-icon svg-icon-sm svg-icon-heavy mr-xl-2">
                  <use xlink:href="#time-1"> </use>
                </svg>Upcoming Events </a>
            </li>
              <li class="sidebar-item"><a id="search-lnk" class="sidebar-link" href="{{ url_for('phototainment.search_event') }}">
                <svg class="svg-icon svg-icon-sm svg-icon-heavy mr-xl-2">
                  <use xlink:href="#find-1"> </use>
                </svg>Search Events </a>
            </li>
              <li class="sidebar-item"><a id="add-lnk" class="sidebar-link" href="{{ url_for('phototainment.add_event') }}">
                <svg class="svg-icon svg-icon-sm svg-icon-heavy mr-xl-2">
                  <use xlink:href="#survey-1"> </use>
                </svg>Create Booking</a>
            </li>

              <li class="sidebar-item"><a id="change-pass" class="sidebar-link" href="{{ url_for('phototainment.change_password') }}">
                <svg class="svg-icon svg-icon-sm svg-icon-heavy mr-xl-2">
                    <use xlink:href="#key-1"></use>
                </svg>Change Password</a>
            </li>
              <li class="sidebar-item logout-btn"><a class="sidebar-link" href="{{ url_for('phototainment.logout') }}">
                <i class="fas fa-sign-out-alt mr-3"></i>Logout</a>
            </li>


          </ul>
        </nav>

app/templates/start-up.html
{% extends 'base.html' %}
{% block title %}Index{% endblock %}

            {% block content %}
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
            {% endblock %}

{% block custom_scripts %}
<script>
       document.getElementById('sidebarCollapse').classList.add("disp-none")
</script>
{% endblock %}